use_frameworks!
target 'TrackLocations_Example' do
  pod 'TrackLocations', :path => '../'

  target 'TrackLocations_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 1.0.0'
  pod 'Nimble', '~> 5.1.1'
  pod 'Alamofire'
  pod 'SwiftyJSON'
  
#  post_install do |installer|
#      installer.pods_project.targets.each do |target|
#          target.build_configurations.each do |config|
#              config.build_settings["SWIFT_VERSION"] = '3.0'
#          end
#    end
  end
  

end
