use_frameworks!

target 'TrackLocations_Example' do
  pod 'TrackLocations', :path => '../'

  target 'TrackLocations_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 1.0.0'
  pod 'Nimble', '~> 5.1.1'
  end
end
